FORMAT: 1A
TITLE: FIWARE-GlanceSync API v1 Specification
DATE: 24 November 2015
VERSION: v1.0
APIARY_PROJECT: glancesync


# FIWARE GlanceSync

<!--
Copyright 2015 Telefónica I+D
All Rights Reserved.
Licensed under the Apache License, Version 2.0 (the "License"); you may
not use this file except in compliance with the License. You may obtain
a copy of the License at
        http://www.apache.org/licenses/LICENSE-2.0
Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
License for the specific language governing permissions and limitations
under the License.
-->

The FIWARE GlanceSync tools is developed under the FIWARE Ops tool 
and it is used to synchronise the glance images in the different 
Glance servers connected in the FIWARE Lab.

Although this component has been developed for FIWARE, the software 
is highly configurable, do not have special requirements beyond 
OpenStack libraries and may be used with any other project or as 
a generic tool to synchronise images. Moreover, all the OpenStack 
interface is in a module and it is possible to adapt the code to 
support other platforms.

## Editors

  + Fernando López Aguilar, Telefónica I+D

## Copyright

This specification is licensed under the
[FIWARE Open Specification License](http://forge.fiware.org/plugins/mediawiki/wiki/fiware/index.php/FI-WARE_Open_Specification_Legal_Notice_%28essential_patents_license%29).

## Status

Final version aligned with FIWARE Release 5.1.


# Group glancesync v1

## API authentication
All the operations, except the information of the service, in the 
GlanceSync API needs to have a valid token to access it. To obtain 
the token, you need to have an account in FIWARE Lab 
(account.lab.fi-ware.org). With the credentials (username, password 
and tenantName) you can obtain a valid token.

The GlanceSync API returns the 404 Not Found error code if you provide 
a token that it is not validate or it is expired. Besides, GlanceSync 
API returns the 401 Unauthorized error code if the role of the token 
is not authorized to realize the operation.

## Faults

The error code is returned in the body of the response for convenience. 
The message section returns a human-readable message that is appropriate 
for display to the end user. The details section is optional and may 
contain information—for example, a stack trace—to assist in tracking 
down an error. The detail section may or may not be appropriate for 
display to an end user.

<table>
    <tr><td><b>Fault Element</b></td><td><b>HTTP code</b></td><td><b>Description</b></td></tr>
    <tr><td>Compute Fault</td><td>400, 500, other codes possible</td><td>Error in the operation</td></tr>
    <tr><td>serviceUnavailable</td><td>503</td><td>The service is not available</td></tr>
    <tr><td>badRequest</td><td>400</td><td>The request has not been done correctly</td></tr>
    <tr><td>unauthorized</td><td>401</td><td>You are not authorized to access to that operation. The token is not correct.</td></tr>
    <tr><td>itemNotFound</td><td>404</td><td>It is not exist</td></tr>
    <tr><td>badMethod</td><td>405</td><td>Method not allowed</td></tr>
    <tr><td>badRegion</td><td>410</td><td>Region does not exist</td></tr>
</table>

## API version [/]

### Get information about GlanceSync API [GET]

Lists information about GlanceSync API version.

+ Request

    + Headers
    
            X-Auth-Token: token-id

+ Response 200 (application/json)

        {
        "id": "v1.0",
        "owner": "Telefonica I+D",
        "status": "SUPPORTED",
        "version": "1.0",
        "updated": "2011-01-21T11:33:21Z",
        "runningfrom": "2011-01-21T11:33:21Z",
        "href": "https://github.com/telefonicaid/fiware-glancesync",
        }
