#!/bin/bash
#
# Copyright 2015 Telefónica Investigación y Desarrollo, S.A.U
#
# This file is part of FI-Core project.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
#
# You may obtain a copy of the License at:
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#
# See the License for the specific language governing permissions and
# limitations under the License.
#
# For those usages not covered by the Apache version 2.0 License please
# contact with opensource@tid.es
#


export PATH=/usr/bin:$PATH ; export PYTHONPATH=/usr/lib/python2.7/dist-packages
nova secgroup-create allopen "all open"
nova secgroup-add-rule allopen icmp -1 -1 0.0.0.0/0
nova secgroup-add-rule allopen tcp 1 65535 0.0.0.0/0
nova secgroup-add-rule allopen udp 1 65535 0.0.0.0/0
nova secgroup-create sshopen "ssh open"
nova secgroup-add-rule sshopen tcp 22 22 0.0.0.0/0

rm -f ~/.ssh/createtestimage
nova keypair-add  createimage > ~/.ssh/createtestimage
chmod 400 ~/.ssh/createtestimage

IP=$(nova floating-ip-list | awk '/^\|[ ]+[0-9]+/ { print $2 }')
if [ ! $IP ] ; then
nova floating-ip-create public-ext-net-01
fi
