FROM centos
RUN yum install -y epel-release
RUN yum update -y 
RUN yum install -y crudini gcc libffi-devel  openssl-devel git gcc build-essentials python-devel python-pip
RUN mkdir /opt/fiware
RUN git clone https://github.com/telefonicaid/fiware-glancesync/ /opt/fiware/glancesync/
WORKDIR /opt/fiware/glancesync/tests/acceptance/
COPY settings.json conf/settings.json
RUN pip install -r requirements.txt
RUN pip install docopt
COPY glancesync.conf /etc/glancesync.conf
RUN pip install python-openstackclient
RUN mkdir /var/lib/glance
RUN mkdir /var/lib/glance/images
COPY start_acceptance.sh start.sh
CMD ./start.sh

